services:
  - type: web
    name: agentic-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false